[package]
name = "meerkat-cli"
version = "0.1.0"
edition = "2021"

authors = ["Paul W."]
description = "Parses a TOML file and outputs a JSON file"

[[bin]]
name = "meerkat"
path = "src/main.rs"

[dependencies]
clap = { version = "3", features = ["derive"] }
serde_json = "1"
toml = "0.5"
